import React, { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Head from "next/head";
/* import { BrowserRouter, Route, Switch } from "react-router-dom"; */

const Nav = () => {
	
		const [darkMode, setDarkMode] = useState(false);
	
		return (
			<div className={darkMode ? "dark" : ""}>
				<Head>
					<title>Portfolio Web App Full stack</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className=" bg-star-light px-10 h-20 dark:star-light-ceniza md:px-20 lg:px-40">
					<section className="min-h-screen">
						<nav className="py-1 mb-12 flex bg-star-light sticky top-0 z-50 justify-between dark:text-white">
							<h1 className="font-starjedi text-xl">Portfolio Web App Full stack</h1>
							<ul className="flex items-center">
								<li>
									<BsFillMoonStarsFill
										onClick={() => setDarkMode(!darkMode)}
										className=" cursor-pointer text-2xl"
									/>
								</li>
								<li>
									<a
										className="bg-gradient-to-r from-star-light-tone text- to-star-light text-white px-4 py-2 border-none rounded-md ml-8"
										href="#"
									>
										Contáctame!
									</a>
								</li>
							</ul>
						</nav>
						</section>
						</main>
						</div>
		)
}
/* function Home() {
	return <>Home</>
}

function Contact() {
	return <>Contact</>;
} */

export default Nav;
